[package]
name = "server"
version = "1.0.0"
authors = ["Jia Ye <planet0104@gmail.com>"]

[dependencies]
tank = { path = "../tank" }
ws = "0.7.6"
serde_json = "1.0.13"
uuid = { version = "0.6", features = ["v4"] }
num = "0.1.42"