[package]
name = "server"
version = "1.0.0"
authors = ["Jia Ye <planet0104@gmail.com>"]

[dependencies]
tank = { path = "../tank" }
#ws = "0.7.6"
uuid = { version = "0.6", features = ["v4"] }
num = "0.1.42"
websocket = "0.20.2"
tokio-core = "0.1.17"
futures = "0.1.21"
futures-cpupool = "0.1.8"