[package]
name = "tank"
version = "0.1.0"
authors = ["Jia Ye <planet0104@gmail.com>"]

[dependencies]
rand = "0.4.2"
uuid = { version = "0.6", features = ["v4"] }
serde = "1.0.37"
serde_json = "1.0.13"
serde_derive = "1.0.37"